[workspace]
authors = ["alejandrofontan <fontanvillacampa@gmail.com>"]
channels = ["conda-forge"]
name = "alejandrofontan.github.io"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
preview = "bundle exec jekyll serve --livereload"

[dependencies]
